### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by windy664** [We-Cant-Coding/TACZ-Fabric#3] opened 2024-07-23 03:31 UTC
**Describe the bug**
开启新存档，启动

然后就游戏崩溃了

[latest.log](https://github.com/user-attachments/files/16343350/latest.log)

fabric 0.15.11
fabric-api-0.92.2

**Comment by windy664** [comment] 2024-07-23 03:33
“Currently if you add porting-lib mod into your mods folder, it will be broken.” 
此话何解？是装有porting-lib的mod都没法共存吗？
诸如create，Hephaestus，也用了这个lib

**Comment by LaeDev** [comment] 2024-07-23 06:07
> 此话何解？是装有porting-lib的mod都没法共存吗？
> 诸如create，Hephaestus，也用了这个lib

Currently, We are looking in this kind of bug.

**Comment by windy664** [comment] 2024-07-23 06:09
> > 此话何解？是装有porting-lib的mod都没法共存吗？
> > 诸如create，Hephaestus，也用了这个lib
> 
> Currently, We are looking in this kind of bug.

我刚刚用服务器能正常运行，但是它好像不支持中文路径

**Comment by LaeDev** [comment] 2024-07-23 06:24
> > > 此话何解？是装有porting-lib的mod都没法共存吗？
> 
> > > 诸如create，Hephaestus，也用了这个lib
> 
> > 
> 
> > Currently, We are looking in this kind of bug.
> 
> 
> 
> 我刚刚用服务器能正常运行，但是它好像不支持中文路径
> 
> 
> 
> [14:08:37] [main/ERROR]: Failed to start the minecraft server
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tacz-fabric'!
> 
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
> 
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
> 
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
> 
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
> 
> 	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
> 
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
> 
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
> 
> 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
> 
> 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
> 
> Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 9: file:/D:/[1.20]风铃物语群组-Fabric/家园二区/mods/tacz-fabric-1.0.0.jar!/assets/tacz-fabric/custom/tacz_default_gun
> 
> 	at java.net.URI.create(URI.java:903) ~[?:?]
> 
> 	at com.tacz.guns.util.GetJarResources.getTargetPath(GetJarResources.java:113) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.util.GetJarResources.lambda$copyFolder$0(GetJarResources.java:93) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
> 
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
> 
> 	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
> 
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
> 
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
> 
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
> 
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
> 
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
> 
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
> 
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
> 
> 	at com.tacz.guns.util.GetJarResources.copyFolder(GetJarResources.java:92) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.util.GetJarResources.copyModDirectory(GetJarResources.java:52) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.resource.CommonGunPackLoader.checkDefaultPack(CommonGunPackLoader.java:106) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.resource.CommonGunPackLoader.init(CommonGunPackLoader.java:63) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.resource.DedicatedServerReloadManager.loadGunPack(DedicatedServerReloadManager.java:9) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.GunMod.onInitialize(GunMod.java:50) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
> 
> 	... 6 more
> 
> Caused by: java.net.URISyntaxException: Illegal character in path at index 9: file:/D:/[1.20]风铃物语群组-Fabric/家园二区/mods/tacz-fabric-1.0.0.jar!/assets/tacz-fabric/custom/tacz_default_gun
> 
> 	at java.net.URI$Parser.fail(URI.java:2970) ~[?:?]
> 
> 	at java.net.URI$Parser.checkChars(URI.java:3141) ~[?:?]
> 
> 	at java.net.URI$Parser.parseHierarchical(URI.java:3223) ~[?:?]
> 
> 	at java.net.URI$Parser.parse(URI.java:3171) ~[?:?]
> 
> 	at java.net.URI.<init>(URI.java:620) ~[?:?]
> 
> 	at java.net.URI.create(URI.java:901) ~[?:?]
> 
> 	at com.tacz.guns.util.GetJarResources.getTargetPath(GetJarResources.java:113) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.util.GetJarResources.lambda$copyFolder$0(GetJarResources.java:93) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
> 
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
> 
> 	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
> 
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
> 
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
> 
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
> 
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
> 
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
> 
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
> 
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
> 
> 	at com.tacz.guns.util.GetJarResources.copyFolder(GetJarResources.java:92) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.util.GetJarResources.copyModDirectory(GetJarResources.java:52) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.resource.CommonGunPackLoader.checkDefaultPack(CommonGunPackLoader.java:106) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.resource.CommonGunPackLoader.init(CommonGunPackLoader.java:63) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.resource.DedicatedServerReloadManager.loadGunPack(DedicatedServerReloadManager.java:9) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at com.tacz.guns.GunMod.onInitialize(GunMod.java:50) ~[tacz-fabric-1.0.0.jar:?]
> 
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
> 
> 	... 6 more
> 
> 
> 
> 如果服务器存放在英文路径，服务器就能正常运行

I'll take a look at that as well.

**Comment by LaeDev** [comment] 2024-07-23 16:37
We have confirmed that this is not a bug related to Chinese paths. We believe the bug is related to the create mod you mentioned above. We will include a bugfix in the next commit and release.

**Comment by LaeDev** [comment] 2024-07-26 10:31
We've included special character support in the next hotfix, just in case.

**Comment by LaeDev** [comment] 2024-07-29 07:55
Fixed in 1.0.2

**Closed by LaeDev** 2024-07-29 07:55 UTC
Labels: bug
